### ISSUE TITLE
Touchpad, touchscreen and keyboard drivers don't work.

### ISSUE THREAD

**Issue by JustAnEric** [coolstar/driverinstallers#12]
My drivers return this error:

This device is currently waiting on another device or set of devices to start. (Code 51)

Dependencies:
PCI\VEN_8086&DEV_31BA&SUBSYS_72708086&REV_03\3&b1bfb68&0&BB
ACPI\INT3453\2

FIX

**Comment by coolstar** [comment]
RW_LEGACY is not supported. Flash the full rom
