### ISSUE TITLE
NO keyboard backlight 

### ISSUE THREAD

**Issue by lcluna86** [coolstar/driverinstallers#16]
keyboard is working fine on lenovo yoga c13 ryzen 5 3500C  128GB windows 11 uefi firmware but no keyboard backlight

**Comment by yunerduo** [comment]
I also have the same problem.

**Comment by rosanyadav08** [comment]
Please give solution for this

**Comment by coolstar** [comment]
should be fixed in recent crosec drivers. You may need to install the AMD tablet mode detection driver if you're still having issues
