### ISSUE TITLE
board taeko may have ec issue.

### ISSUE THREAD

**Issue by krrrak** [coolstar/driverinstallers#18]
I have flashed "full rom".
######
1.CPU0 always at 100% showed in task manager.
2.System interrupts often higher than 2% CPU, sometimes even up to 15%.
3.discharge too fast, which never lower than 18w.
######
By the way, these problem I have mentioned do not appear on Linux. And system interrupts seems to work correctly with altfw, but touchscreen always not work.

**Comment by coolstar** [comment]
Issue with coreboot, not with drivers.
