### ISSUE TITLE
about samus audio card

### ISSUE THREAD

**Issue by asd2asd** [coolstar/driverinstallers#3]
I'm very sorry to bother you, want to know if there is any hope for the windows driver of goolgle chromebook pixel 2 's  sound card ,RT5677

**Comment by coolstar** [comment]
Driver will be available this week

**Comment by asd2asd** [comment]
Thank you for your amazing work!

**Comment by coolstar** [comment]
https://github.com/coolstar/driverinstallers/blob/master/csaudiosstcatpt/csaudiosstcatpt.1.0-installer.exe
