### ISSUE TITLE
Chell audio doesn't work after reboot

### ISSUE THREAD

**Issue by Munichokay** [coolstar/driverinstallers#4]
My device is HP chromebook 13 g1 AKA Chell with a skylake processor. The audio works perfectly just after installation, but everytime I reboot there won't be any sound output. Only if I reinstall the ssm4567 driver the audio will be working again.
BTW, even when there's no audio output, the device is still recognised by windows and the audio seems to work just fine in the settings.

**Comment by coolstar** [comment]
Fixed in AVS driver
