### ISSUE TITLE
keyboard backlight

### ISSUE THREAD

**Issue by Tony-Yes** [coolstar/driverinstallers#5]
Can't I manually adjust the brightness or switch after the keyboard backlight driver is installed? Can't find a way to adjust, my device is flex5 and the operating system is Windows 11

**Comment by wuc9521** [comment]
Yes I cannot adjust my keyboard backlight neither, my device is Pixelbook Go and OS is win11

**Comment by coolstar** [comment]
Supported with crosec 2.x / croskeyboard4
