### ISSUE TITLE
Chromebook elan touchscreen 2.9.3.0 not active

### ISSUE THREAD

**Issue by smx06** [coolstar/driverinstallers#6]
Windows 10 x64 (21h2, the same on earlier builds and ver 2.9.2.0) 
From device manager
Device status:
This device cannot find enough free resources that it can use. (Code 12)
If you want to use this device, you will need to disable one of the other devices on this system
Location:
on Intel(R) Serial IO I2C Host Controller - 9D60
hID:
ACPI\VEN_ELAN&DEV_0001&SUBSYS_1AE0006C

Events:
Device ACPI\ELAN0001\0 had a problem starting.

Driver Name: oem202.inf
Class Guid: {745a17a0-74d3-11d0-b6fe-00a0c90f57da}
Service: CrosTouchScreen

Lower Filters: 
Upper Filters: mshidkmdf
Problem: 0xC
Problem Status: 0xC0000018

p.s. if disabling Intel(R) Serial IO I2C Host Controller - 9D60 itself (in system devices) 
elan touchscreen device disappears also (i.e. doesn't go to other available 9d62, 9d63 controllers)

**Comment by coolstar** [comment]
Update to latest coreboot to fix this
