### ISSUE TITLE
DELL 7410

### ISSUE THREAD

**Issue by geochensx** [coolstar/driverinstallers#9]
Hello! On your website I saw that the DELL 7410 laptop, touchscreen and touchpad worked normally, but I tested the two drivers you published (touchpad and touchscreen) and they still didn't work with WIndows10 and windows11. Excuse me, is there any special operation required?
I am currently using coreboot 4.19.1 and I am not sure if this is the cause.

**Comment by coolstar** [comment]
Fixed in coreboot updates
